# Schema for trezor connect settings, and mappings.
trezor_connect.settings:
  type: config_object
  label: 'Trezor Connect Settings'
  mapping:
    text:
      type: string
      label: 'Login Text'
    text_register:
      type: string
      label: 'Register Text'
    text_manage:
      type: string
      label: 'Authentication Device Text'
    text_manage_admin:
      type: string
      label: 'Authentication Device Admin Text'
    external:
      type: integer
      label: 'Use CDN'
    url:
      type: string
      label: 'External TREZOR Connect Javascript URL'
    callback:
      type: string
      label: 'TREZOR Connect Callback'
    flood_threshold:
      type: integer
      label: 'Flood Threshold'
    flood_window:
      type: integer
      label: 'Flood Window'
    challenge_offset:
      type: integer
      label: 'Challenge Offset'
    challenge_backend:
      type: string
      label: 'TREZOR Connect challenge backend'
    challenge_response_backend:
      type: string
      label: 'TREZOR Connect challenge response backend'
    mapping_backend:
      type: string
      label: 'TREZOR Connect mapping backend'

trezor_connect.mappings.*:
  type: config_entity
  label: 'Trezor Connect Mapping'
  mapping:
    id:
      type: string
      label: 'ID'
    created:
      type: integer
      label: 'Created'
    uid:
      type: integer
      label: 'UID'
    challenge_hidden:
      type: string
      label: 'Hidden Challenge'
    challenge_visual:
      type: string
      label: 'Visual Challenge'
    address:
      type: string
      label: 'Address'
    public_key:
      type: string
      label: 'Public Key'
    signature:
      type: string
      label: 'Signature'
